name: Package Seed Test
description: Provide a description here
author: Fern

# Action branding. This will appear on the GitHub Marketplace. CHRISM - this true? repo is private
branding:
  icon: box
  color: green

# Define inputs
inputs:
  seed-generator-alias:
    description: The alias of the seed generator to use
    required: true
  number-of-packages:
    description: The number of packages to group the tests into (Note - may have one additional package depending on add-package-for-leftovers setting)
    required: true
  add-package-for-leftovers:
    description: Whether to add a package for leftover tests or not.
    required: true
  split-tests-cutoff-time-in-seconds:
    description: The cutoff time in seconds to split tests into multiple runners
    required: true
  seed-test-log-file-path:
    description: Log file to parse test output from
    required: true

# Define outputs
outputs:
  json-file-contents:
    description: "All information in JSON format for packaging tests"

runs:
  using: node24
  main: dist/index.js
