name: Package Seed Test
description: Provide a description here
author: Fern

# Action branding. This will appear on the GitHub Marketplace. CHRISM - this true? repo is private
branding:
  icon: box
  color: green

# Define inputs
inputs:
  seed-generator-alias:
    description: The alias of the seed generator to use
    required: true
  max-runner-count:
    description:
      The maximum number of runners that can be used (determines upper limit of
      packages)
    required: true
  seed-test-log-file-path:
    description: Log file to parse test output from
    required: true

# Define outputs
outputs:
  test-matrix:
    description: 'Packaged test matrix'
    # value: ${{ steps.package-test-matrices.outputs.packaged }}
  split-tests:
    description: 'Whether to split tests into multiple runners or run as one' #CHRISM - can we determine this in post by packages=1?
    # value: ${{ steps.determine-test-setups.outputs.split-tests }}

runs:
  using: node24
  main: dist/index.js
