name: Group Seed Tests
description: Provide a description here
author: Fern

# Action branding. This will appear on the GitHub Marketplace.
branding:
  icon: box
  color: green

# Define inputs
inputs:
  number-of-groups:
    description: The number of groups to group the tests into
    required: true
  seed-test-log-file-path:
    description: Log file to parse test output from
    required: true

# Define outputs
outputs:
  json-file-contents:
    description: "All information in JSON format for grouping tests"

runs:
  using: node24
  main: dist/index.js
